#!/usr/bin/python3
"""Module to contain class definition of a State and an
    instance base. The class inherits from the Base
"""


from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, Integer, String


Base = declarative_base()


class State(Base):
    """Class state inherits from Base
        links to the MySQL tables states

        Attributes:
            id - column of autogenerated unique integer
            name - column for string with maximum 128 characters.
    """
    __tablename__ = 'states'

    id = Column(Integer, autoincrement=True, primary_key=True)
    name = Column(String(128), nullable=False)
